name: $name
version: $version
description: $description
api-version: "$apiVersion"
main: com.github.drakepork.regionteleport.RegionTeleport
depend: [WorldGuard]
softdepend: [CMI, Essentials, PlaceholderAPI]
author: DrakePork
permissions:
  regionteleport.command.*:
    description: Gives access to all regiontp commands
    children:
      regionteleport.command.help: true
      regionteleport.command.setspawn: true
      regionteleport.command.delspawn: true
      regionteleport.command.spawnlist: true
      regionteleport.command.teleport: true
      regionteleport.command.clear: true
  regionteleport.teleport.bypass:
    description: Does so you dont get teleported from the region
    default: false

